### PR TITLE
Adding materialize command

### LINKED ISSUE #101: Add a materialize command to material inferred superclasses (named and existential)
## Motivation

Consider the following class, together with its axiom in a source/editors file

```
[Term]
id: GO:0002080
name: acrosomal membrane
intersection_of: GO:0098805 ! whole membrane
intersection_of: bounding_layer_of GO:0001669 ! acrosomal vesicle
```

The `reason` command will produce an extra subClassOf axiom:

```
id: GO:0002080
name: acrosomal membrane
is_a: GO:0030667 ! secretory granule membrane
intersection_of: GO:0098805 ! whole membrane
intersection_of: bounding_layer_of GO:0001669 ! acrosomal vesicle
```

(assuming additional axioms, e.g. acrosomal vesicle is a secretory vesicle, and axiomatization of SGM)

This is valid, but is not sufficient for the case where the consumer of the ontology wishes to traverse existential graphs over properties such as part-of

The `relax` command (#7) partially addresses this, in that it will create an additional:

```
relationship: bounding_layer_of GO:0001669 ! acrosomal vesicle
```

However, if we then wish to filter object properties this loses information
## Materialize

This will use the [EMR](https://github.com/owlcollab/expression-materializing-reasoner/) to materialize direct superclasses, named and existential. The set of existentials can be restricted by property.

For example, it should be possible to do compose the materialize command with `reduce`:

```
    robot materialize --reasoner ELK --input emr_example.obo --term BFO:0000050 filter -t BFO:0000050 reduce --output results/emr_reduced.obo
```

This should write all direct inferred axioms `C SubClassOf part-of some D` (as well as C SubClassOf D), where D is a named class.

The resulting SubClassOf graph is then guaranteed to be complete for part-of

In the example above, we would have:

```
id: GO:0002080
name: acrosomal membrane
namespace: cellular_component
def: "The membrane that surrounds the acrosomal lumen. The acrosome is a special type of lysosome in the head of a spermatozoon that contains acid hydrolases and is concerned with the breakdown of the outer membrane of the ovum during fertilization." [GOC:dph]
is_a: GO:0030667 ! secretory granule membrane
relationship: part_of GO:0001669 ! acrosomal vesicle
```

cc @dosumis

### PR DESCRIPTION
**Pull request by cmungall**
Fixes #101

### CODE REVIEW

**Comment by cmungall** [comment]
@dosumis - makes sense?

Note that a nice side effect is that this works as expected for GCIs

**Comment by jamesaoverton** [comment]
Why drop Java 7 support in this PR?

**Comment by cmungall** [comment]
Dependency on the ExpressionMaterializingReasoner - https://github.com/owlcollab/expression-materializing-reasoner/ - but maybe there is some java-fu I'm missing here, may be possible to cross-compile?

**Comment by jamesaoverton** [comment]
If we're dropping Java 7, then that should be a separate PR.

I'm a bit worried about the consequences. Travis doesn't seem to support OpenJDK 8. So dropping support for OpenJDK 7 means only testing OracleJDK. I'd like people to be able to use ROBOT with OpenJDK.

The feature is fine. `mvn clean site` shows some style problems. I can fix them if you don't have time.

**Comment by cmungall** [comment]
I'm not sure if the lack of travis support for openjdk8 prevents anyone from using openjdk8.

I could look at backporting EMR to be java7, but we are java8 for everything now, my vote would be to just make the jump

**Comment by jamesaoverton** [comment]
Is this good to go?

**Comment by cmungall** [comment]
Yes. If you're happy with the java8 switch.

**Comment by jamesaoverton** [comment]
Ok. I updated Java8 in #103. I'll merge this now.

**Pull request merged**
