### PR TITLE
Add metrics command first pass

### PR DESCRIPTION
**Pull request by matentzn**
Resolves [#627]

- [x] `docs/` have been added/updated
- [x] tests have been added/updated
- [x] `mvn verify` says all tests pass
- [x] `mvn site` says all JavaDocs correct
- [x] `CHANGELOG.md` has been updated

ROBOT jar for testing [here](https://www.dropbox.com/s/3wr8lcuz3pkopoo/robot.jar?dl=0).

For the community, the most relevant question will be which of the metrics should go in which bin (essential, extended, advanced):

#### Entity counts
- SIGNATURE_SIZE_INCL
- SIGNATURE_SIZE
- CLASS_COUNT_INCL
- CLASS_COUNT
- OBJPROPERTY_COUNT_INCL
- OBJPROPERTY_COUNT
- INDIVIDUAL_COUNT_INCL
- INDIVIDUAL_COUNT
- DATAPROPERTY_COUNT_INCL
- DATAPROPERTY_COUNT
- ANNOTATION_PROP_COUNT
- ANNOTATION_PROP_COUNT_INCL
- DATATYPE_COUNT_INCL
- DATATYPE_COUNT

#### Axiom counts
- LOGICAL_AXIOM_COUNT
- LOGICAL_AXIOM_COUNT_INCL
- AXIOM_COUNT
- AXIOM_COUNT_INCL
- TBOX_SIZE
- TBOX_SIZE_INCL
- TBOXRBOX_SIZE
- TBOXRBOX_SIZE_INCL
- RULE_CT
- RULE_CT_INCL
- RBOX_SIZE
- RBOX_SIZE_INCL
- ABOX_SIZE
- ABOX_SIZE_INCL

#### OWL Profile metrics
- BOOL_PROFILE_OWL
- BOOL_PROFILE_OWL
- BOOL_PROFILE_OWL
- BOOL_PROFILE_OWL
- BOOL_PROFILE_OWL
- BOOL_PROFILE_RDFS
- VIOLATION_PROFILE_OWL

#### Other metrics
- OWLAPI_VERSION
- ONTOLOGY_ID
- ONTOLOGY_ANNOTATIONS_COUNT
- VALID_IMPORTS
- VALID_IMPORTS_INCL

#### Extended entity metrics
- DATATYPE_BUILTIN_COUNT_INCL
- DATATYPE_BUILTIN_COUNT
- DATATYPE_NOTBUILTIN_COUNT_INCL
- DATATYPE_NOTBUILTIN_COUNT

#### Logical expressivity
- EXPRESSIVITY
- EXPRESSIVITY_INCL
- CONSTRUCTS_INCL
- CONSTRUCTS
- AXIOM_TYPES
- AXIOM_TYPES_INCL
- AXIOMTYPE_COUNT
- AXIOMTYPE_COUNT_INCL
- SYNTAX

#### Entity usage
- NS_USE_AXIOMS
- NS_USE_AXIOMS_INCL
- NS_USE_SIGNATURE
- NS_USE_SIGNATURE_INCL

### Advanced metrics (all)
- MAX_AXIOMLENGTH
- MAX_AXIOMLENGTH_INCL
- AVG_ASSERT_N_SUBCLASS_INCL
- AVG_ASSERT_N_SUBCLASS
- AVG_ASSERT_N_SUPERCLASS_INCL
- AVG_ASSERT_N_SUPERCLASS
- AVG_INSTANCE_PER_CLASS_INCL
- AVG_INSTANCE_PER_CLASS
- CLASS_SGL_SUBCLASS_COUNT_INCL
- CLASS_SGL_SUBCLASS_COUNT
- AXIOM_COMPLEXRHS_COUNT_INCL
- AXIOM_COMPLEXRHS_COUNT
- TBOX_CONTAINS_NOMINALS_INCL
- TBOX_CONTAINS_NOMINALS
- ABOX_CONTAINS_NOMINALS_INCL
- ABOX_CONTAINS_NOMINALS
- GCI_COUNT_INCL
- GCI_COUNT
- GCI_HIDDEN_COUNT_INCL
- GCI_HIDDEN_COUNT
- MAX_NUM_NAMED_SUPERCLASS_INCL
- MAX_NUM_NAMED_SUPERCLASS
- MULTI_INHERITANCE_COUNT_INCL
- MULTI_INHERITANCE_COUNT
- REF_CLASS_COUNT
- REF_DATAPROP_COUNT_INCL
- REF_DATAPROP_COUNT
- REF_INDIV_COUNT_INCL
- REF_INDIV_COUNT
- REF_OBJPROP_COUNT_INCL
- REF_OBJPROP_COUNT
- UNDECLARED_ENTITY_COUNT_INCL
- UNDECLARED_ENTITY_COUNT
- TAUTOLOGYCOUNT
- TAUTOLOGYCOUNT_INCL
- CYCLE
- CYCLE_INCL
- CYCLE
- CYCLE
- DATATYPE_AXIOMCOUNT
- DATATYPE_AXIOMCOUNT_INCL
- DATATYPES
- DATATYPES_INCL
- DATATYPES_NOT_BUILT_IN
- DATATYPES_NOT_BUILT_IN_INCL
- MOST_FRQUENTLY_USED_CONCEPT_INCL
- MOST_FRQUENTLY_USED_CONCEPT

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Very cool.

I ran this on [MRO](https://github.com/IEDB/MRO) since I was working on it. It's about 50MB of OWL, and `metrics` says it's 56360 TBox axioms. Some immediate feedback:

- I don't love the `_incl` name but I don't have a better suggestion
- I'd prefer that the format be automatically detected based on the extension of `--output`, with `--format` overriding if specified; there's code for this elsewhere in ROBOT
- `.csv` format should be supported
- I'd prefer to see all options for `--metrics` in the CLI help message
- the default `--metrics essential` took about 10 seconds to run, while `--metrics all` took almost 20 minutes; I guess that's not a surprise
- the YAML output starts with `---` which surprised me; there's no closing `---`
- `owlapi_version: "robot.jar"` seems weird
- I'd like the docs to spell out (or link to more information about) some of the abbreviations, such as `constructs` and `expressivity`

Overall, the full set of metrics has interesting information that I'll spend some time digesting.

**Comment by matentzn** [comment]
> I don't love the _incl name but I don't have a better suggestion

maybe `_imports`? or `_imp`? The alternative is a separate column in the table for incl/excluding imports. I am open, the way we do it hear is how I used to do it during my PhD a while back, so I am not wedded it it!

> I'd prefer that the format be automatically detected based on the extension of --output, with --format overriding if specified; there's code for this elsewhere in ROBOT. 
> .csv format should be supported


OK!

- [ ] Implement extension based format detection
- [ ] add CSV format
- [ ] add all options for --metrics in the CLI help message

> the default --metrics essential took about 10 seconds to run, while --metrics all took almost 20 minutes; I guess that's not a surprise

Nope, makes sense. The cycle detection and tautology computation takes a long time.

> the YAML output starts with --- which surprised me; there's no closing ---

Yeah, check this: https://stackoverflow.com/questions/50788277/why-3-dashes-hyphen-in-yaml-file (first answer). I don't like this much either.

> owlapi_version: "robot.jar" seems weird

makes no sense anymore.. I used this hack back in the days to determine the correct owlapi version used - there is no way I can see to do so from within Java, unless anyone else knows of one.

- [ ] Remove `owlapi_version` metric

> I'd like the docs to spell out (or link to more information about) some of the abbreviations, such as constructs and expressivity

- [ ] Spell out all abbreviations in docs

@jamesaoverton Thank you for the review!

**Comment by jamesaoverton** [comment]
I've never seen `---` used in the wild except to separate multiple YAML "documents" in the same file, or separate a YAML header from Markdown (the most common). In practise, the dashes seem to be optional for a single YAML document in a single file. I've never seen YAML directives in the wild, either.

I admit that the YAML 1.2 spec does use dashes a lot, but it's also including the `%YAML 1.2` directive in each of those examples: <https://yaml.org/spec/1.2/spec.html>.

**Comment by matentzn** [comment]
Ok I fixed the YAML thing using: https://stackoverflow.com/questions/46445834/writing-java-object-instance-to-yaml-using-jackson

**Comment by matentzn** [comment]
Ok, last thing:

>  Spell out all abbreviations in docs

What do you mean exactly - the possible _values_ or the abbreviations used in the names of the metrics (like `_incl`, etc). You want to know what say: `construct: [AL, I]` means?

**Comment by jamesaoverton** [comment]
Yes, I don't know what `construct: [AL, I]` means. That's what I meant, but the other additions in 49b9d9924de46a456cbaa86b9ebcead0aa1a8a61 are great.

**Comment by matentzn** [comment]
Ok, I think I am done with the first round of feedback (thanks a ton @jamesaoverton!). I have also uploaded a new version [here](https://www.dropbox.com/s/3wr8lcuz3pkopoo/robot.jar?dl=0).

**Pull request merged**
