### PR TITLE
Add --check option to convert

### PR DESCRIPTION
**Pull request by rctauber**
`--check false` allows the user to ignore the OBO document structure rules, see #64 

By default, `--check` is true.

Updated documentation included.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
@cmungall or @dougli1sqrd Can you see if this works for your use cases?

**Comment by jamesaoverton** [comment]
@cmungall or @dougli1sqrd does this solve #64 for you?

**Comment by jamesaoverton** [comment]
Testing this with `convert -i obi.owl -o obi.obo` (without `--check`) results in an empty `obi.obo` file. Failures should not generate empty files.

**Comment by rctauber** [comment]
Merging, looking into fix for the empty output here: https://github.com/owlcs/owlapi/issues/741

**Pull request merged**
