### PR TITLE
WIP: Adding guide on how to handle import closure with imports

### PR DESCRIPTION
**Pull request by cmungall**
I believe the documented behavior is true, but should be checked

### CODE REVIEW

**Comment by cmungall** [comment]
Hmm, I'm not so sure how useful my advice is. I am trying to get RO to pass and it's hard.

If I don't merge, then entities are missing labels.

If I do merge, I get dupe labels (since labels for IAO_0000115 are MIREOTed in to the imported ontologies)

**Comment by matentzn** [comment]
Please ignore this comment, since its pure hack alert: I think you can get around some of these issues by deleting Declarations of foreign terms. I dont remember why this works (or whether it even should work), but I think it does. Obviously, this wont work with ROBOT (since its using the OWL API for serialisation, so you cant remove Declarations), but you can hack your way with sed.

**Comment by jamesaoverton** [comment]
Your advice for `report` is good, and worth adding to the docs.

The dashboard should be run on a base artifact -- that seems like a separate issue?

**Comment by jamesaoverton** [comment]
@beckyjackson Can you please review this, and merge if it looks good to you?

**Review by beckyjackson — APPROVED** [review]

**Pull request merged**
