### PR TITLE
Apply google java format for #134

### PR DESCRIPTION
**Pull request by rctauber**
Auto formatting with google java format (https://github.com/google/google-java-format) as per #134

### CODE REVIEW

**Comment by jamesaoverton** [comment]
All the tests pass. I did some manual tests and things seem fine. I looked around and the source code is much more consistent. @rctauber is looking into enforcing the style automatically.

Since the indentation changes from four spaces to two spaces, pretty much every line of Java in the repository is modified. If we merge this, there will be a "wall" in our version history that will take an extra step to see over. But as we get more contributions, I'll be much happier to focus on the *content* of changes, and never worry about formatting again.

@cmungall: What do you think?

**Comment by cmungall** [comment]
Sounds good but let's wait til all other PRs are merged?

**Comment by jamesaoverton** [comment]
I’m happy to wait a while. Some of the PRs are getting pretty old.

**Comment by rctauber** [comment]
Closing to redo once all other PRs are merged

**Pull request closed without merging**
