### PR TITLE
update mapping examples in rename docs

### PR DESCRIPTION
**Pull request by reality**
replace commas in example mapping files with the required tabs

### CODE REVIEW

**Comment by reality** [comment]
When I tried it with a comma I got a message about expecting two columns but getting only one. The problem here, I think, is that I copied the command examples from this document, so my filename had a ".tsv." suffix, but was using commas as delimiters (per the example). I assume robot is using the filename suffix to determine the format? For consistency we could either accept this change, or instead change the command examples to use .csv filenames?

**Comment by reality** [comment]
(the latter may be better since I think copying tabs from github can be problematic sometimes)

**Comment by jamesaoverton** [comment]
Now I understand, and I agree: the format of the example table should match the file extension in the command-line example. In this case, I think making both CSV would be better, for the reason you point to about copy-pasting tabs.

**Comment by jamesaoverton** [comment]
I changed my mind: Let's consistenly use TSV here.

**Pull request merged**
