### PR TITLE
Restoring previous version

### PR DESCRIPTION
**Pull request by cmungall**
Accidentally committed experimental changes to master previously

### CODE REVIEW

**Comment by rctauber** [comment]
The `FILTER (?property != owl:deprecated))` should probably stay, as that's how the query should be... I'm not totally sure why I did a string match on the IRI there.

I was doing a string match on `owl:deprecated true` to make sure to catch any instances where people might accidentally use a string instead of a boolean.

**Comment by dougli1sqrd** [comment]
This PR in particular was to restore what was there originally since Chris' changes got messed up. But I think we're probably not in much danger from accidentally using string true, since won't this run on obo files most of the time?

**Comment by cmungall** [comment]
@dougli1sqrd I don't understand the relevance of obo files here.

All: apologies for the confusion. I accidentally committed my original changes to master. This PR is to restore things to how they were so we can then properly evaluate my changes as a PR with travis checks etc. But probably best to abandon this PR and work from master...

**Comment by dougli1sqrd** [comment]
@cmungall I just meant that in robot obo will convert to correct OWL which will use actual true/false values, rather than string "true".

**Comment by jamesaoverton** [comment]
@cmungall No worries. We can lock `master` on this repo if you prefer.

Sorry, but I don't understand what to do with this PR at this point. Please either merge or close, as you see fit.

**Comment by cmungall** [comment]
Let's just work off of what we have in master

**Pull request closed without merging**
