### PR TITLE
Fill gaps in filter/remove

### PR DESCRIPTION
**Pull request by rctauber**
See #263

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Does this have any tests? It's not clear to me whether `remove_class.owl` is being used for an integration test since it seems like a new file, but it's mentioned in the previous `remove.md`.

**Comment by rctauber** [comment]
That shouldn't be in there - sorry - it was part of the `results`. I'll swap that out and add an integration test for this.

**Comment by jamesaoverton** [comment]
@rctauber Can you please resolve this merge conflict?

**Comment by rctauber** [comment]
Do we want to change the default behavior of `--trim` to `true`? I know we talked about it a bit but I wasn't sure if I should implement that in this branch.

**Comment by jamesaoverton** [comment]
Let's do that in a new PR, after this is merged.

**Comment by jamesaoverton** [comment]
@ontodev/robot-team and maybe @balhoff and @matentzn in particular: This is an important improvement to remove/filter, but I'm worried that it will be a big performance hit. Can you please test this branch on any remove/filter tasks that you have set up?

I'd like to push a new release soon, so I'd really appreciate some quick feedback. Thanks!

**Comment by jamesaoverton** [comment]
@ontodev/robot-team One more ping on this PR. This is the last big thing we're waiting on for 1.2.0, so I'd really appreciate some quick feedback.

**Comment by balhoff** [comment]
I'm testing one of my targets.

**Comment by balhoff** [comment]
On the targets where I use filter, I don't see any performance impact. However I don't think the options I use require any gap filling.

**Pull request merged**
