### PR TITLE
Add labels option to diff

### PR DESCRIPTION
**Pull request by rctauber**
See #361

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Looks good. I'd like a test, please.

**Comment by rctauber** [comment]
I changed `--use-labels` to `--labels` to match what we do with `report`. I can change it back if you prefer the first version, though.

**Comment by jamesaoverton** [comment]
Yeah, I think `--labels` is better.

**Comment by jamesaoverton** [comment]
Closes #361

**Pull request merged**
