### PR TITLE
Fixed URL pointing to OWLAPI ModuleType

### PR DESCRIPTION
**Pull request by agbeltran**

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Much appreciated! ROBOT uses OWLAPI 4 (like Protege). I'll make that change and merge.

**Comment by agbeltran** [comment]
sorry! I've changed it thinking I hadn't put the latest version

**Comment by agbeltran** [comment]
Changing it back to 4

**Comment by agbeltran** [comment]
You can merge now...

**Comment by jamesaoverton** [comment]
Thanks again!

**Pull request merged**
