### PR TITLE
Added support for JFact

### PR DESCRIPTION
**Pull request by balhoff**
This adds the [JFact DL reasoner](http://jfact.sourceforge.net). This possibly addresses #105.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
More reasoners is good. Does JFact support as much as HermiT? Does it pull a pile of dependencies?

It would be good for the `--help` to list all the available reasoners.

I think you forgot to commit the `simple_jfact.owl` test file.

**Comment by balhoff** [comment]
Not too many new dependencies: depends on OWL API (already included), trove4j (already required by OWL API), joda-time, RoaringBitmap, and a couple others for tests.

I think HermiT is more complete than JFact, but JFact is significantly faster for certain ontologies, such as RO.

**Comment by jamesaoverton** [comment]
Sounds good. I'll give it a test drive tomorrow before merging.

**Comment by jamesaoverton** [comment]
Seems to work. I found it took 5x as long as HermiT for OBI, and 75x as long for my development copy of [MRO](https://github.com/IEDB/MRO). Reasoners are weird.

**Pull request merged**
