### PR TITLE
Verify command

### PR DESCRIPTION
**Pull request by dougli1sqrd**
for https://github.com/ontodev/robot/issues/177

### CODE REVIEW

**Comment by cmungall** [comment]
Logic looks fine once test is added...

...but I want to check about the decision to implement as a separate command rather than an option - we went through this discussion when implementing `construct`:

https://github.com/ontodev/robot/issues/159#issuecomment-294157848

I thought we decided there that construct and verify should be options for `query`?

Sorry I may have mislead by using the term 'subcommand' in the ticket.

What do you think @jamesaoverton

**Comment by dougli1sqrd** [comment]
Ah I see. It's kind of nice this in it's own command, but it wouldn't be hard to move to query either.

**Comment by jamesaoverton** [comment]
I had been thinking of it being part of `query`, but my reasons are mostly for easier implementation. From the user's perspective, this distinct `verify` subcommand seems to be better. The exit code behaviour is very different from `query`, for one thing.

If the output target is a directory, then I think `--report-dir` is a better name than `--report`.

**Comment by jamesaoverton** [comment]
An advantage to putting verify inside `query` is that it can be slow and expensive to populate the triplestore, and currently we aren't putting the triplestore in the CommandState to pass to the next command in the chain. How likely are we to select then verify, or verify then select, and/or do we want to add the triplestore to the CommandState?

Thinking ahead, if we're constructing, then we probably want to do more work with the new triples, so we probably want to pass them down the chain. But then we have to worry about passing the triplestore or repacking it as an OWLOntology.

**Comment by dougli1sqrd** [comment]
I agree that `report-dir` is probably better, I can change that. With verify as a command, I could pass forward the command state instead of ignoring it like I am now. Should the `--input, -i` parameter _replace_ the existing ontology in the `CommandState` or should it update somehow? 

And `construct` I guess doesn't put anything in the command state? We could pass it in to the command state.

**Comment by jamesaoverton** [comment]
The thing is that `CommandState` only includes an `OWLOntology`, not the `DatasetGraph` for the triple store. You're currently just returning the `inputState` unchanged, which is fine because this command should not make any changes to the ontology. If the next command wants to do some SPARQL thing, it will have to build a new `DatasetGraph`, which is relatively expensive. On the other hand, throwing out the `DatasetGraph` saves memory. On the third hand, a construct operation would change the triples, then would we want to pass a new `OWLOntology` or the modified `DatasetGraph` to the next command?

The proposed implementation of verify is probably what we want. I think you should go ahead.

I just worry (like I always do) about regretting something later. The worrying never helps. :^)

**Comment by dougli1sqrd** [comment]
Okay sounds good. I'll change to `report-dir`, and then we'll just leave this as is for now. We can always change the behavior to something else in case we end up developing a use case for construct -> verify. I think we don't have to worry in this case, because this solution is still pretty flexible.

**Comment by jamesaoverton** [comment]
I'm trying this out with OBI. If there are no results, should a report file be generated?

**Comment by cmungall** [comment]
I'd say yes. We need this functioning makefile.

**Comment by jamesaoverton** [comment]
Doing some more work with OBI... The `--report-dir` and `--queries` options for this `verify` command are convenient, but they're totally different from the `query` command options, so it's annoying to switch the behaviour of a single query from "throw errors" to "just warn me". We can change or add to the `query` options, but I'm not sure how we would distinguish select and construct. We could replace `query` with `select` and `construct`. I dunno.

This might be an opportunity for "documentation driven development", where we write the docs first, then adjust the implementation to match.

**Comment by jamesaoverton** [comment]
My proposal in #182 is a superset of this `verify` command, with one exception: I now think that `--report-dir` should be `--output-dir` with short option `-O`, which will be more consistent with other commands.

I think that we should make that small change and merge this PR today. I need this for OBI stuff ASAP.

**Comment by cmungall** [comment]
+1

OK, we'll get this done!

**Comment by dougli1sqrd** [comment]
@jamesaoverton Yeah, you should always get output when you run the verify. And a report file is generated even if there are no results in the results-dir. Is that not happening for you?

**Comment by jamesaoverton** [comment]
@dougli1sqrd Yes, I always get output. If the test passes, then the output file only contains the header line. I was just asking if that was more useful to delete files with just a header, but I agree with @cmungall that deleting them would cause problems for Make. The current implementation is good.

**Comment by dougli1sqrd** [comment]
What do we think of my change from last week, based on @jamesaoverton's suggestion? I'm also working on that broader sparql query robot proposal we discussed.

**Comment by cmungall** [comment]
Ok, let's go ahead and merge, but we also need an example in examples/README

**Comment by dougli1sqrd** [comment]
Cool. Here'a  ticket to make examples: https://github.com/ontodev/robot/issues/186

**Comment by dougli1sqrd** [comment]
So the verify command exiting with 1 if it finds violations is the "spec" I was using since that's what the perl script does we were using previously. However, in examples/readme.md, since we literally run those examples in the unit tests (that fact should be documented probably since I wasn't expecting the examples to be test code also) and it assumes that all commands exit 0, we have a problem. Since the example I use shows a violation sparql rule. Any suggestions?

**Comment by jamesaoverton** [comment]
Hmm. The code is very particular in looking for indented lines started with `robot`. You could use Markdown "code fences" instead: triple backticks or tildes.

James

**Pull request merged**
