### PR TITLE
Ensure that the set of axioms used to test for addition of duplicates is the set present at the initial state

### PR DESCRIPTION
**Pull request by cmungall**
Relevant to #85

### CODE REVIEW

**Comment by cmungall** [comment]
Prior to this PR we had the issue that the go new inferences file (generated using the `-n` option, added in #81) included axioms that were trivially redundant with axioms in the main ontology. E.g. 

```
[Term]
id: GO:0030054 ! cell junction
is_a: GO:0005575 {is_inferred="true"} ! cellular_component
```

Note that this is both a true axiom, and a *direct* inferred axiom. While we were specifying `-s` to remove redundant axioms, this was not removed since by the current definition of removal of redundant axioms (see #85) this was not removed, as it was direct (no intermediate superclasses).

The `-x` option was intended to handle this case. It prohibits the addition of duplicate axioms during the reason operation. However, it was not working as intended in combination with `-n`: in the above case, the `SubClassOf(cell-junction cellular-component)` axiom is not formally a duplicate, since the new ontology is created as a standalone ontology, intended to be imported.

This PR fixes the situation by changing the semantics of `-x` to be do not add anything that duplicates *any axiom present at the initial state, prior to `-n`*.

**Comment by jamesaoverton** [comment]
This seems straightforward. Please merge it when you're ready.

**Comment by dosumis** [comment]
> do not add anything that duplicates any axiom present at the initial state, prior to -n.

This sounds like the correct behaviour to me.  Spot checking test file of GO inferences.

**Comment by dosumis** [comment]
Spot checking looks good.

Number of tagged inferred GO annotations back to similar numbers to those before change:

* last tuesday's GO file had 88781
* using latest GO + test GO inferred annotations file => 88638.  Expected slightly less due to deletion of stale axioms, but probably OK.

**Pull request merged**
