### PR TITLE
Update deprecated_class_reference.rq

### PR DESCRIPTION
**Pull request by matentzn**
Takes care of performance issue discussed on slack (the other suggestions were too slow on large ontologies).

### CODE REVIEW

**Comment by beckyjackson** [comment]
Are we OK with "entity" being empty? That last `UNION` doesn't have an `?entity` binding, so it will only show the property & value. The entity is a blank node, anyway, for which we were referencing blank node IDs before. Blank node IDs are pretty unhelpful, so I think either leaving the column blank or binding "blank node" as `?entity` are both good options.

**Comment by beckyjackson** [comment]
I can also confirm that this is MUCH faster 🙂

**Comment by matentzn** [comment]
I dont mind either way! You can decide what to bind, not to bind.. I think empty column is fine.

**Comment by beckyjackson** [comment]
@jamesaoverton - should we leave the "entity" column blank on a blank node, or bind "blank node" for this column?

**Comment by jamesaoverton** [comment]
I prefer "blank node". But if we're doing something else in other checks then it's more important to be consistent with that.

**Comment by beckyjackson** [comment]
Currently in other checks, we use a blank node ID, which isn't helpful. I believe @matentzn mentioned in another issue replacing these blank node IDs.

**Comment by jamesaoverton** [comment]
@matentzn is off for a few days. Let's wait for him to chime in.

**Comment by matentzn** [comment]
I prefer `blank node`, see https://github.com/ontodev/robot/issues/873

And yes, we should do this everywhere across the board. :) I volunteer if no one else wants.

**Comment by beckyjackson** [comment]
@matentzn - I can take care of it, but it won't be for a little bit. Can you just update this PR to use "blank node" and then I'll merge it?

**Pull request merged**
