### PR TITLE
Add --strict flag

### LINKED ISSUE #785: "Unparsed triple" errors for models with reification and annotation properties
I'm trying to use `merge` to merge together an ontology and a file with a set of entities that have annotation properties.  This second file is generated by flattening Turtle* to Turtle with `RDFstarTools`.

I'm getting floods of `INFO` messages about "Unparsed triple"s.

These seem to be for *any* triple whose predicate is `rdf:subject`, `rdf:predicate` or `rdf:object` or that are of the form *URL* `rdf:type` `rdf:Statement`.

*Should* I even expect this to work?

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #785 

- [x] `docs/` have been added/updated
- [x] tests have been added/updated
- [x] `mvn verify` says all tests pass
- [ ] `mvn site` says all JavaDocs correct
- [x] `CHANGELOG.md` has been updated

First pass at adding a `--strict` global flag that causes ROBOT to fail on unparsed triples. By default, unparsed triples will now be parsed as errors. I also added a hint about RDF reification if `rdfs:Statement` is found as an object.

The `--strict` flag also turns on strict parsing with OWLAPI, but I couldn't find any documentation about what that means. If anybody (@ontodev/robot-team) knows where I can find those details (or has a brief summary) that would be great!

Additionally, are there other examples of issues that cause unparsed triples? I'd like to make sure the documentation does a good job of explaining how to fix the issue.

### CODE REVIEW

**Comment by beckyjackson** [comment]
Error message for untyped predicates:
```
UNPARSED TRIPLES ERROR input ontology contains 1 triple(s) that could not be parsed:
 - <urn:robot:reificationExample:Bb65616dcX2Dde2dX2D405aX2Da1aaX2Ddfbb25f03995> <urn:robot:reificationExample:propertyOne> :propertyOne.

Hint: you have untyped predicates - try adding 'rdf:type' declarations to the following:
 - urn:robot:reificationExample:propertyOne
```

Error message for RDF reification:
```
UNPARSED TRIPLES ERROR input ontology contains 4 triple(s) that could not be parsed:
 - <urn:robot:reificationExample:Bb65616dcX2Dde2dX2D405aX2Da1aaX2Ddfbb25f03995> <http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate> <urn:robot:reificationExample:indicatedBy>.
 - <urn:robot:reificationExample:Bb65616dcX2Dde2dX2D405aX2Da1aaX2Ddfbb25f03995> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2000/01/rdf-schema#Statement>.
 - <urn:robot:reificationExample:Bb65616dcX2Dde2dX2D405aX2Da1aaX2Ddfbb25f03995> <http://www.w3.org/1999/02/22-rdf-syntax-ns#object> <urn:robot:reificationExample:Bar>.
 - <urn:robot:reificationExample:Bb65616dcX2Dde2dX2D405aX2Da1aaX2Ddfbb25f03995> <http://www.w3.org/1999/02/22-rdf-syntax-ns#subject> <urn:robot:reificationExample:Foo>.

Hint: you may be using RDF reification - try replacing 'rdfs:Statement' with 'owl:Axiom'
```

One other type of error is these gen IDs... These are in our unit tests:
```
_:genid2147484004 <http://www.w3.org/2002/07/owl#annotatedTarget> test 3 comment.
_:genid2147484004 <http://www.w3.org/2002/07/owl#annotatedSource> _:genid-nodeid-4.
_:genid2147484004 <http://www.w3.org/2002/07/owl#annotatedProperty> <http://www.w3.org/2000/01/rdf-schema#comment>.
```

These are for third-level nested annotation axioms:
image

... and the OWL looks like this:
```
 <Annotation>
        <annotatedSource>
            <Axiom rdf:nodeID="genid4">
                <annotatedSource rdf:resource="http://purl.obolibrary.org/obo/GO_1234"/>
                <annotatedProperty rdf:resource="http://www.w3.org/2000/01/rdf-schema#label"/>
                <annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">test 3</annotatedTarget>
                <rdfs:comment xml:lang="en">test 3 comment</rdfs:comment>
                <rdfs:seeAlso rdf:resource="http://robot.obolibrary.org/"/>
            </Axiom>
        </annotatedSource>
        <annotatedProperty rdf:resource="http://www.w3.org/2000/01/rdf-schema#comment"/>
        <annotatedTarget xml:lang="en">test 3 comment</annotatedTarget>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">test 3 comment comment</rdfs:comment>
    </Annotation>
```

Even though it says they're unparsed, running `robot convert` keeps these. I'm not totally sure what to do about these ones.

**Comment by balhoff** [comment]
@beckyjackson:

> Even though it says they're unparsed, running robot convert keeps these. I'm not totally sure what to do about these ones. 

 @ignazio1977 made this comment in https://github.com/owlcs/owlapi/issues/988:

> Main problem is that the leftover triples are not very reliable - often I see info messages of that sort that seem incorrect, so some investigation might be required first.

Maybe this is a good test case to resolve that! (third-level nested annotation axioms)

**Comment by jamesaoverton** [comment]
I looked through the docs and the code and I'm happy with it, but can we please have some sort of test? (Probably a unit test in this case.)

**Review by jamesaoverton — CHANGES_REQUESTED** [review]
Looks great but please add some sort of unit test.

**Review by jamesaoverton — APPROVED** [review]
Thanks! Please merge when you're ready.

**Pull request merged**
