### PR TITLE
Release 1.7.1

### LINKED ISSUE #751: Plan for 1.7.1 release
We should make a patch release of ROBOT with recent changes. It's a bit more of a pain than usual because I don't want to release the `validate` command yet.

This is the plan:

- fix #750 and merge
- make a `v1.7.x` branch from `master`, then on the new branch:
    - remove `ValidateCommand.java` and `ValidateOperation.java`
    - remove `validate` command from [ComandLineInterface.java](https://github.com/ontodev/robot/blob/master/robot-command/src/main/java/org/obolibrary/robot/CommandLineInterface.java#L45)
    - edit the CHAGELOG.md to clarify what's in 1.7.1
- make a release `v1.7.1` from `v1.7.x`

Thoughts @beckyjackson @balhoff ?

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #751

This removes `validate` from ROBOT for release v1.7.1.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
These are the right changes. Thanks!

We don't want to merge it into `master`, so I marked as a Draft.

I'll turn this into a release tomorrow.

**Comment by jamesaoverton** [comment]
Sorry, I'm slow (as usual). The JavaDocs need to be fixed.

**Review by jamesaoverton — CHANGES_REQUESTED** [review]
@beckyjackson please fix the JavaDocs so that `mvn clean site` passes.

**Comment by beckyjackson** [comment]
Doc strings fixed in #755 and merged into this PR.

**Comment by jamesaoverton** [comment]
Ok, I finally released this as https://github.com/ontodev/robot/releases/tag/v1.7.1

**Pull request closed without merging**
