### PR TITLE
Handle symlinks to robot script on gnu and bsd.

### LINKED ISSUE #242: Handle symlinking to robot script
Allow users to symlink to the robot script.

- Support the convention /opt (or /usr/local) and linking to the executable.
- Does not require modifying PATH

This would add a level of complexity to the shell script beyond just using `readlink -f` because that will not work on Macs.

### PR DESCRIPTION
**Pull request by grosscol**
Closes #242

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Much appreciated! I'll take a look at this as soon as I get a chance.

**Comment by jamesaoverton** [comment]
This worked for me and @rctauber.

@cmungall and @dougli1sqrd: Please test (if you want to) then merge this.

**Comment by cmungall** [comment]
@kltm - @dougli1sqrd will check this works on our jenkins setup

**Comment by dougli1sqrd** [comment]
We just merge this and then run the pipeline in the faster "iteration" branch to make sure this works.

**Comment by jamesaoverton** [comment]
Thanks again for the PR @grosscol!

**Comment by dougli1sqrd** [comment]
This worked in our test build.

**Pull request merged**
