### PR TITLE
Display the help when no argument is given on the command line.

### PR DESCRIPTION
**Pull request by bjonnh**
It is still a bit redundant to make if/else if with return statements, but it solves the issue. We could make it cleaner by first checking arg length and then doing the case by case.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Much appreciated! And good to meet you this week.

@rctauber Please add a fix for the underlying problem to this PR:

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 4
at java.lang.String.substring(String.java:1963)
at org.obolibrary.robot.ExceptionHelper.getExceptionID(ExceptionHelper.java:50)
```

**Comment by rctauber** [comment]
Just added a fix for that to the exception helper. Should be good to go!

**Comment by jamesaoverton** [comment]
Fixed #332. Thanks again @bjonnh !

**Comment by bjonnh** [comment]
Glad to meet both of you this week too. Keep up with the good work! This is a great tool.

**Pull request merged**
