### PR TITLE
Update OBOgraphs JSON

### PR DESCRIPTION
**Pull request by matentzn**
Resolves [#933]

- [ ] `docs/` have been added/updated
- [ ] tests have been added/updated
- [ ] `mvn verify` says all tests pass
- [ ] `mvn site` says all JavaDocs correct
- [ ] `CHANGELOG.md` has been updated

a new version of obographs added to ROBOT..

### CODE REVIEW

**Comment by matentzn** [comment]
Sigh, not on maven central..

**Comment by matentzn** [comment]
Blocked by https://github.com/ontodev/robot/issues/935 

- Does not work with Java 8

**Comment by matentzn** [comment]
This should definitely go into the next ROBOT release!

**Comment by jamesaoverton** [comment]
Yes, we have a bunch of stuff to merge, then we can make a new release.

@matentzn Please update this branch from `master` and hopefully #990 fixes the tests on this branch.

**Comment by matentzn** [comment]
Thanks @balhoff already did this! :)

**Comment by jamesaoverton** [comment]
This passed the GitHub actions, but it broke [`master` on Jenkins](https://build.obolibrary.io/job/ontodev/job/robot/job/master/174/console) and also locally for me:

```
/Users/james/Repositories/github/ontodev/robot/robot-core/src/main/java/org/obolibrary/robot/IOHelper.java:[32,42] cannot access org.geneontology.obographs.core.io.OgJsonGenerator   
  bad class file: /Users/james/.m2/repository/org/geneontology/obographs/obographs-core/0.3.0/obographs-core-0.3.0.jar(org/geneontology/obographs/core/io/OgJsonGenerator.class)              
    class file has wrong version 55.0, should be 52.0                                                                                                                                         
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

Anybody recognize this error?

**Comment by jamesaoverton** [comment]
Ok, thanks. I was still using Java 8 to build locally. When I updated to Java 11 the build succeeded. I'll ask about updating Jenkins.

**Pull request merged**
