### PR TITLE
Additional options for reason command to annotate inferences and place new inferences in a separate ontology

### PR DESCRIPTION
**Pull request by cmungall**
aded create-new-ontology option in ReasonerOperation for #66
TODO: Tests, command, #67

### CODE REVIEW

**Comment by cmungall** [comment]
@jamesaoverton - any comments?

The use case here is the GO one where we want to place new inferences in a new file.

It somehow doesn't feel quite right to rewrite the input ontology, but as the operation doesn't return an ontology not sure how else to do that without a bigger refactor

**Comment by jamesaoverton** [comment]
This is how I handled something similar for the `template` command: https://github.com/ontodev/robot/blob/master/docs/template.md#merging

It's not a great solution. Yours probably makes more sense for this command.

Can you set your editor to use four spaces instead of tabs, please?

**Comment by cmungall** [comment]
Ready to merge pending approval from @jamesaoverton 

Note all tabs are gone

**Comment by jamesaoverton** [comment]
Thanks. I'll take a closer look this afternoon and merge it unless I have big questions.

**Pull request merged**
