### PR TITLE
Change OBO provider to CURIE provider

### PR DESCRIPTION
**Pull request by beckyjackson**
- [x] `docs/` have been added/updated
- [x] tests have been added/updated
- [x] `mvn verify` says all tests pass
- [ ] `mvn site` says all JavaDocs correct
- [ ] `CHANGELOG.md` has been updated

Fix provider used for short form IDs in `export` to match the IRI to longest namespace possible. If no match is found in prefixes, return the full IRI and log an error.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
I'd like a few more unit tests for the CURIE provider, please. We should have tests for "overlapping" prefixes to be absolutely sure that the longer base is used.

**Comment by beckyjackson** [comment]
@jamesaoverton - I've added a test for a few IRIs. Please let me know if you want any more tested.

**Comment by jamesaoverton** [comment]
@beckyjackson That covers the important cases. Thanks!

@ontodev/robot-team This change addresses a problem we had in `export` where the current ShortFormProviders will just make up a prefix if no matching prefix is defined. This code will log an error and return the IRI string if it can't find a prefix.

Should it just be a warning? Should we fail harder?

**Comment by jamesaoverton** [comment]
No comments in more than a week, so I'm going to merge.

**Pull request merged**
